name: Checks

on: [push]

jobs: 
  test-lint:
    name: Test and List
    runs-on: ubuntu-20.04
    steps: 
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install Docker Compose
        run: |
           sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/
           docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
           sudo chmod +x /usr/local/bin/docker-compose

      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: |
           pip install flake8
           flake8
           docker-compose run --rm app sh -c "flake8"

